name: Test
on:
  pull_request
jobs: 
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: install deps
        run: yarn

      - name: build
        run: ./node_modules/lerna/cli.js run build
        
      - name: test
        run: ./node_modules/lerna/cli.js run test
